### ISSUE TITLE
Remove unnecessary hash code test for a value object

### ISSUE THREAD

**Issue by monrealis** [vkhorikov/DddInAction#1]
I am sure it is not the requirement that objects that are not equal have different hash codes. It is just by accident, though very probable, that this test passes. There are more different objects that different hash codes.

https://github.com/vkhorikov/DddInAction/blob/484c5b51e79e1f3973675fa017df3673862acca8/DddInPractice.Tests/MoneySpecs.cs#L46

P.S. Thanks for your great course.

**Comment by vkhorikov** [comment]
Huh, indeed. You are exactly correct, this assertion is invalid per se.

**Comment by vkhorikov** [comment]
Fixed, closing.
